version: '3'

services:
  kcal:
    build:
      context: .
      dockerfile: Dockerfile
    image: kcal
    container_name: kcal
    restart: unless-stopped
    networks:
      - network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - kcal
    networks:
      - network

volumes:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/daniel/git/kcal/frontend/public/
      o: bind

networks:
  network:
    driver: bridge